name: Create ECR Repository

on:
  workflow_dispatch:
    inputs:
      ecr_repository_name:
        description: "ECR repository name"
        required: true
        type: string
      aws_region:
        description: "AWS region, e.g. us-east-2"
        required: false
        type: string
        default: "us-east-2"

jobs:
  create-ecr:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Create ECR repository
        run: |
          aws ecr create-repository \
            --repository-name "${{ inputs.ecr_repository_name }}" \
            --region "${{ inputs.aws_region }}" \
            || echo "Error creating ECR repository. It may already exist."